PREFIX sf:<http://skripsifinder.com/skripsi#>

SELECT ?judul ?nama ?npm ?peminatan ?tahun
WHERE
{
  ?s  sf:judul ?judul ;
      sf:nama ?nama ;
      sf:npm ?npm ;
      sf:hasPeminatan ?namaPeminatan ;
      sf:isTahun ?TahunSkripsi .


  ?namaPeminatan sf:peminatan ?peminatan .
  ?TahunSkripsi sf:tahun ?tahun .
}